baseURL = 'https://imax.in.ua/'
languageCode = 'en-us'
title = 'imax'
theme = 'gokarna'

[params]
  description = "Some random nerd on them internets"
  metaKeywords = ["homepage"]
  images = [""]

  socialIcons = [
    {name = "github", url = "https://github.com/imax9000/"},
    {name = "bluesky", url = "https://bsky.app/profile/hack.imax.in.ua"},
    {name = "discord", url = "https://discordapp.com/users/379475972509925377"},
  ]
